# top level stuff you probably don't need to touch
highlighter: rouge
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://brh.github.io/
baseurl: /sustain/
title: Bobby Hargett
author: Bobby Hargett
description: Blog about Development, but mostly Java, in a Android world.
avatar: profile.png
email: yourname@email.com
github: brh # username
twitter: brh_jr
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: 


# needed for travis-ci build
exclude: [vendor]
